boss(X) :-
	write('ini abis cukup quest selesai buat unlock jalan ke final boss\n'),
	nl,
	write('Mendengar banyaknya tubes yang telah diselesaikan '),
	write(X),
	write(', Raja Naga Keri pun mengundangnya untuk datang ke istananya.\n'),
	nl,
	write('---------------Di Istana---------------\n'),
	nl,
	write('"Selamat datang hero '),
	write(X),
	write(' di istanaku."\n'),
	write('"Saya, Raja Naga Keri, ingin berterimakasih atas jasa Anda terhadap dunia ini mengalahkan tubes2 blablabla..."\n'),
	nl,
	write('Sudah burnout marathon mengerjakan banyak tubes,'),
	write(X),
	write(' tidak tahan mendengarkan pidato raja yang panjang dan bertele-tele.\n'),
	write('Ia pun memotong pidato raja untuk menanyakan kapan dia bisa pulang ke dunianya karena dia masih dikejar deadline tubes di ITB.\n'),
	nl,
	write('"Pulang? Tapi kami membutuhkan Anda di sini! Siapalagi yang akan membantu saya mengerjakan semua tubes ini!"\n'),
	nl,
	write(X),
	write(' tetap bersikukuh dia ingin pulang, membuat Raja Naga Keri marah.\n'),
	nl,
	write('"OK, kalau begitu saya tantang Anda untuk duel dengan saya. Kalau saya kalah Anda boleh pulang,\n'),
	write('tapi kalau saya menang Anda harus menggantikan saya sebagai raja dan mengerjakan semua tubes di Jurusan."\n'),
	nl,
	write('Berpikir duelnya konyol dan buat apa dia menerima duelnya, '),
	write(X),
	write(' pun menolak.\n'),
	nl,
	write('"Hah apa maksud lu nolak duel, ga bisa gitu dong. Pokoknya kita duel sekarang!!"\n'),
	nl,
	write('-------------BOSS BATTLE BEGINS!!!----------\n'),
	nl,
	write('----------------BOSS DEFEATED----------------\n').
	