tpb(X) :-
	nl,
	write(X), 
	write(' adalah seseorang mahasiswa IF ITB yang stres dengan tubesnya. \nOleh karena itu, dia pun memutuskan untuk pergi ke indomaret untuk rehat. \nNamun saat menyebrang jalan ke indomaret '),
	write(X),
	write(' ditabrak oleh truck-kun dan dia pun pergi ke isekai, yaitu dunia "Jurusan". \n'),
	nl,
	write(X),
	write(' pun terbangun di sebuah gedung bernama TPB. Di sini ia disambut oleh seseorang yang dikenal dengan sebutan Paus Asdos.\n'),
	write('Paus Asdos mengatakan bahwa '),
	write(X),
	write(' telah disummon ke dunia lain untuk membantu dunia "Jurusan" untuk membantu masyarakatnya melawan wabah monster tubes.\n'),
	write('Masih bingung dengan situasinya, Paus Asdos tiba-tiba menyuruh '),
	write(X),
	write(' untuk mengisi formulir job terlebih dahulu sebelum dijelaskan lebih lanjut.\n'),
	nl,
	write(' ----------------------------------------------------\n'),
	write('                      Formulir Job                   \n'),
	nl,
	write('   Welome to Jurusan, o\' brave hero!!\n'),
	nl,
	write('   Nama: '),
	write(X),
	nl,nl,
	write('   Pilih job Anda:\n'),
	nl,
	write('      1. Swordsman\n'),
	write('         Jobdesc:\n'),
	write('            - Defense-Oriented (ez mode)\n'),
	write('            - Base Stats:\n'),
	write('               * Initial Max HP : 800\n'),
	write('               * Attack         : 50\n'),
	write('               * Defense        : 150\n'),
	write('            - Special Attack:\n'),
	write('               * Masochism something2\n'),
	write('                   -> Full counter\n'),
	write('      2. Archer\n'),
	write('         Jobdesc:\n'),
	write('            - Gimmick Oriented\n'),
	write('            - Base Stats:\n'),
	write('               * Initial Max HP : 500\n'),
	write('               * Attack         : 150\n'),
	write('               * Defense        : 50\n'),
	write('            - Special Attack:\n'),
	write('               * Steal!!!\n'),
	write('                   -> Maling item\n'),
	write('      3. Sorcerer\n'),
	write('         Jobdesc:\n'),
	write('            - Gacha Glass Cannon\n'),
	write('            - Base Stats:\n'),
	write('               * Initial Max HP : 400\n'),
	write('               * Attack         : 200\n'),
	write('               * Defense        : 50\n'),
	write('            - Special Attack:\n'),
	write('               * Expurusion, but with gacha\n'),
	write('                   -> Deals 0-9999 damage\n'),
	nl,
	write('   Input: \n'),
	nl,
	write(' ----------------------------------------------------\n'),
	write('anggap aj udh isi\n'),
	write('Sesudah '),
	write(X),
	write(' mengisi formulir jobnya, Paus Asdos pun melanjutkan expositionnya.\n'), 
	nl,
	write('Ia bilang bahwa di dunia ini dewa-dewi Dosen telah memberikan anugerah kepada manusia dalam bentuk tubes.\n'),
	write('Dengan menyelesaikan tubes seseorang akan dapat menerima EXP points dan bisa level up, menjadi lebih hebat dari sebelumnya.\n'),
	nl,
	write('Namun sayangnya banyak masyarakat jurusan yang malas, tidak ingin mengerjakan tubes.\n'),
	write('Daripada mengerjakan, mereka malah memberikan tubes2 mereka ke Raja Keri yang handal mengerjakan tubes.\n'),
	write('Kesal namun tidak bisa menolak, Raja Keri pun menerima dan mencoba untuk mengerjakan tubes2 dari seluruh penjuru Jurusan.\n'),
	write('Karena segala tubes yang telah dikerjakannya ia menjadi sangat kuat dan telah berevolusi menjadi naga, dikenal dengan nama Raja Naga Keri.\n'),
	write('Namun, dia pun akhirnya tenggelam juga banyaknya tubes yang ada.\n'),
	nl,
	write('Marah dan kesal karena tidak ada yang membantu, dia pun mengirimkan semua tubes itu ke seluruh penjuru dunia.\n'),
	write('Tubes-tubes yang tidak dikerjakan ini pun lama-kelamaan jadi terisi dengan energi negatif lalu berubah menjadi monster.\n'),
	write('Monster-monster tubes inilah yang sedang meneror dunia jurusan dan alasan mengapa Anda disummon ke sini.\n'),
	nl,
	write('Anda sebagai mahasiswa IF ITB pastinya sudah terbiasa dan jago dalam mengalahkan tubes.\n'),
	write('Oleh karena itu, tolonglah kami oh pejuang IF ITB, selamatkan kami dari badai tubes ini, hentikan Raja Naga Keri yang marah2, dan selamatkan dunia ini.\n'),
	nl,
	write('Paus Asdos pun tidak menunggu respon '),
	write(X),
	write(' dan langsung menganggap '),
	write(X),
	write(' setuju.\n'),
	write('Ia pun langsung diterjunkan ke tutorial battle melawan sebuah tubes Alstrukdat yang telah berubah menjadi goblin.\n'),
	nl,
	write('Start tutorial battle.\n'),
	write('anggap aj udh selesai\n'),
	nl,
	write('Dengan selesainya tutorial battle ini Paus Asdos pun langsung mengeluarkan '),
	write(X),
	write(' ke dunia Jurusan yang kejam.\n'),
	nl,nl,
	write('ADVENTURE START').
	