tpb(X) :-
	nl,
	write(X), 
	write(' adalah seseorang mahasiswa IF ITB yang stres dengan tubesnya. \nOleh karena itu, dia pun memutuskan untuk pergi ke indomaret untuk rehat. \nNamun saat menyebrang jalan ke indomaret '),
	write(X),
	write(' ditabrak oleh truck-kun dan dia pun pergi ke isekai, yaitu dunia "Jurusan". \n'),
	nl,
	write(X),
	write(' pun terbangun di sebuah gedung bernama TPB. Di sini ia disambut oleh seseorang yang dikenal dengan sebutan Paus Asdos.\n'),
	write('Paus Asdos mengatakan bahwa '),
	write(X),
	write(' telah disummon ke dunia lain untuk membantu dunia "Jurusan" untuk membantu masyarakatnya melawan wabah monster tubes.\n'),
	write('Masih bingung dengan situasinya, Paus Asdos tiba-tiba menyuruh '),
	write(X),
	write(' untuk mengisi formulir job terlebih dahulu sebelum dijelaskan lebih lanjut.\n'),
	nl,
	write(' ----------------------------------------------------\n'),
	write('                      Formulir Job                   \n'),
	nl,
	write('   Welome to Jurusan, o\' brave hero!!\n'),
	nl,
	write('   Nama: '),
	write(X),
	nl,nl,
	write('   Pilih job Anda:\n'),
	nl,
	write('      1. Swordsman\n'),
	write('         Jobdesc:\n'),
	write('            - Defense-Oriented (ez mode)\n'),
	write('            - Base Stats:\n'),
	write('               * Attack : 50\n'),
	write('               * Defense: 150\n'),
	write('            - Special Attack:\n'),
	write('               * Masochism something2\n'),
	write('                 -> Full counter\n'),
	write('      2. Archer\n'),
	write('         Jobdesc:\n'),
	write('            - Gimmick Oriented\n'),
	write('            - Base Stats:\n'),
	write('               * Attack : 150\n'),
	write('               * Defense: 50\n'),
	write('            - Special Attack:\n'),
	write('               * Steal!!!\n'),
	write('                 -> Maling item\n'),
	write('      3. Sorcerer\n'),
	write('         Jobdesc:\n'),
	write('            - Defense-Oriented (for pussies)\n'),
	write('            - Base Stats:\n'),
	write('               * Attack : 200\n'),
	write('               * Defense: 50\n'),
	write('            - Special Attack:\n'),
	write('               * Expurusion, but with gacha\n'),
	write('                 -> Deals 0-9999 damage\n'),
	nl,
	write('   Input: \n'),
	nl,
	write(' ----------------------------------------------------\n').
	